name: Test assignment submission

on:
  push:
    branches:
      - asgn/subn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install otter-grader

    - name: Run Python command
      run: |
        python -m otter check submission_12413885.py
